# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49f6a02c88d590df64325e1952004b16e526b9ebc0257e11eddf20c508527012c46dc27a9ec2238c607ff126544d46534f02630b80b9b802dabefaf8b0bc1b86

test:
  secret_key_base: d9a14ef4682a642d1dbe9d5971ddf91ed16cf474eeaf83644d9819c971f8e5f1b54106e283ad03d3c5cb867a8a07b4ba244b6cb98348bdf2dbd83726a2a4ce88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
